---
- hosts: all
  become: true
  tasks:

  - name: install apache2 package
    ansible.builtin.package:
      name: 
        - apache2
        - libapache2-mod-php
      state: latest
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

