---
- hosts: all
  become: true
  pre_tasks: 

    - name: Install Updates
      tags: always
      ansible.builtin.apt:
        upgrade: dist
        update_cache: yes
      when: ansible_distribution == "Ubuntu"

- hosts: all
  become: true
  roles:
    - base

- hosts: dev
  become: true
  roles:
    - db_servers

- hosts: test
  become: true
  roles:
    - web_servers

